### ISSUE TITLE
[1pt] Add unit and integration testing for the rails components

### ISSUE THREAD

**Issue by yonas44** [yonas44/travelers_hub_back-end#3]
- Use `RSpec` and `Capybara` to perform the tests

**Comment by SelmaNdapanda** [comment]
https://github.com/yonas44/travelers_hub_back-end/pull/29
https://github.com/yonas44/travelers_hub_back-end/pull/28
https://github.com/yonas44/travelers_hub_back-end/pull/27
https://github.com/yonas44/travelers_hub_back-end/pull/25
