### ISSUE TITLE
[1pt] Write unit and integration testing for the react components

### ISSUE THREAD

**Issue by yonas44** [yonas44/travelers_hub_back-end#4]
- Use `React testing library` to perform testing for the componenets.

**Comment by SelmaNdapanda** [comment]
https://github.com/yonas44/travelers_hub_front-end/pull/14
https://github.com/yonas44/travelers_hub_front-end/pull/10
https://github.com/yonas44/travelers_hub_front-end/pull/9
https://github.com/yonas44/travelers_hub_front-end/pull/8
