### ISSUE TITLE
[1pt] Create a splash screen

### ISSUE THREAD

**Issue by yonas44** [yonas44/travelers_hub_back-end#8]
- On the main page, the user can see a list packages.
- Make sure to set up the routes in the App component and create the component.
- In the navigation panel, the user can see links to:
    - Packages   
     - "Booking form.
    - "My reservations".
    - "Add package item (the link is visible to everybody)..
    - "Delete package" (the link is visible to everybody).
- When the user selects a specific item, they can see the details page.
    - In the details page, the user can click the "Reserve" button (in the design you can see the "Configure" button - please replace it with the "Reserve" button).

**Comment by SelmaNdapanda** [comment]
https://github.com/yonas44/travelers_hub_front-end/pull/5
